// Generated by CoffeeScript 1.3.3

/*
Eim v0.1
github.com/rafbgarcia/eimjs.git

Dependencies: jQuery 1.8.2
*/


(function() {

  (function(window) {
    var Eim, Form;
    Eim = {};
    Eim.Form = function(data) {
      return new Form(data);
    };
    Eim.validators = {
      required: function(errMessage) {
        return {
          isValid: function(val) {
            if (typeof val !== 'number') {
              return !!val.trim();
            }
            return true;
          },
          errMessage: errMessage || 'Field is required'
        };
      },
      email: function(errMessage) {
        var regex;
        regex = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;
        return {
          isValid: function(val) {
            if (val && regex.test(val)) {
              return true;
            }
            return false;
          },
          errMessage: errMessage || 'Email is invalid'
        };
      },
      minLength: function(length, errMessage) {
        return {
          isValid: function(val) {
            return val.toString().trim().length >= length;
          },
          errMessage: errMessage || ['The text is too short, minimum length is', length].join(' ')
        };
      },
      maxLength: function(length, errMessage) {
        return {
          isValid: function(val) {
            return val.toString().trim().length <= length;
          },
          errMessage: errMessage || ['The text is too long, maximum length is', length].join(' ')
        };
      },
      betweenLength: function(minLength, maxLength, errMessage) {
        return {
          isValid: function(val) {
            var valLength;
            valLength = val.toString().trim().length;
            return valLength >= minLength && valLength <= maxLength;
          },
          errMessage: errMessage || ['The text must have length between', minLength, 'and', maxLength].join(' ')
        };
      },
      numeric: function(errMessage) {
        return {
          isValid: function(val) {
            return $.isNumeric(val);
          },
          errMessage: errMessage || 'Field accepts only numeric values'
        };
      },
      min: function(value, errMessage) {
        return {
          isValid: function(val) {
            val = parseInt(val, 10);
            return val >= value;
          },
          errMessage: errMessage || ['Minimum value is', value].join(' ')
        };
      },
      max: function(value, errMessage) {
        return {
          isValid: function(val) {
            val = parseInt(val, 10);
            return val <= value;
          },
          errMessage: errMessage || ['Maximum value is', value].join(' ')
        };
      },
      between: function(min, max, errMessage) {
        return {
          isValid: function(val) {
            val = parseInt(val, 10);
            return val >= min && val <= max;
          },
          errMessage: errMessage || ['The value must be between', min, 'and', max].join(' ')
        };
      },
      match: function(field, errMessage) {
        if (typeof field === 'string') {
          field = $(['input[name="', field, '"]'].join(''));
        }
        return {
          isValid: function(val) {
            return field.val() === val;
          },
          errMessage: errMessage || ['Field does not match with field', field.attr('name')].join(' ')
        };
      }
    };
    Eim.Slider = function(_p) {
      return _p = {
        targets: $('#images .item, #descriptions .item'),
        triggers: $('#controls a'),
        targetActiveClass: 'active',
        triggerActiveClass: 'active',
        sliderType: 'numeric',
        needCss: false,
        needBuildTriggersHtml: false
      };
    };
    Eim.sendMessage = function(message, title) {};
    Eim.improveInputFile = function(obj) {
      return obj = obj || $('input:file');
    };
    /*
        Placeholder (for IE only)
        @param callback set a callback if you need to validate your form fields,
               it will be triggered if form has fields with value == placeholder
               callback(fieldsNamesWithErrors, submittedForm)
    */

    Eim.placeholder = function(callback) {
      var errors, forms, inputs, submited, valueEqualsPlaceholder;
      if (navigator.appName === 'Microsoft Internet Explorer') {
        submited = {};
        inputs = $(':input[placeholder]');
        forms = $('form');
        errors = [];
        valueEqualsPlaceholder = function(element) {
          return element.val() === element.attr('placeholder');
        };
        inputs.each(function() {
          var _this;
          _this = $(this);
          return _this.val(_this.attr('placeholder'));
        }).focus(function() {
          var _this;
          _this = $(this);
          if (valueEqualsPlaceholder(_this)) {
            return _this.val('');
          }
        }).blur(function() {
          var _this;
          _this = $(this);
          if (!_this.val()) {
            return _this.val(_this.attr('placeholder'));
          }
        });
        if (typeof callback === 'function') {
          return forms.submit(function(e) {
            var i, that, _inputs;
            errors = [];
            that = $(this);
            i = that.index(forms);
            _inputs = that.find('input[placeholder]');
            if (!submited[i]) {
              e.preventDefault();
              submited[i] = true;
              _inputs.each(function() {
                var _this;
                _this = $(this);
                if (valueEqualsPlaceholder(_this)) {
                  return errors.push(_this);
                }
              });
              if (errors.length) {
                submited[i] = false;
              }
              return callback(errors, that);
            }
          });
        }
      }
    };
    Form = function(data) {
      var formErrors, formFields, _validateField, _validateForm,
        _this = this;
      formFields = data.fields;
      formErrors = {};
      _validateField = function(fieldName, callback) {
        var err, field, fieldValue, i, validator;
        _this.clearErrors(fieldName);
        field = formFields[fieldName];
        fieldValue = field.value;
        validator = field.validators;
        err = false;
        if (validator.hasOwnProperty('isValid')) {
          if (!validator.isValid(fieldValue)) {
            err = validator.errMessage;
            _this.addError(fieldName, err);
            callback(err);
          }
        } else if (validator.length) {
          for (i in validator) {
            if (!field.hasError) {
              if (!validator[i].isValid(fieldValue)) {
                err = validator[i].errMessage;
                _this.addError(fieldName, err);
                callback(err);
              }
            }
          }
        }
        if (!err) {
          return callback();
        }
      };
      _validateForm = function(callback) {
        var error, i;
        error = false;
        for (i in formFields) {
          _validateField(i, function(err) {
            if (err) {
              return error = true;
            }
          });
        }
        return callback(error);
      };
      this.element = data.form;
      this.addError = function(fieldName, error) {
        formErrors[fieldName] = error;
        formFields[fieldName].hasError = true;
        return formFields[fieldName].error = error;
      };
      this.clearErrors = function(fieldName) {
        formErrors[fieldName] = void 0;
        formFields[fieldName].hasError = void 0;
        return formFields[fieldName].error = void 0;
      };
      this.fields = function(name) {
        return (name && formFields[name]) || formFields;
      };
      this.errors = function() {
        return formErrors;
      };
      this.hasErrors = function() {
        var i;
        for (i in formFields) {
          if (formFields[i].hasError) {
            return true;
          }
        }
        return false;
      };
      this.bind = function(data) {
        var i;
        for (i in data) {
          if (formFields.hasOwnProperty(i)) {
            formFields[i].value = data[i];
          }
        }
        return this;
      };
      this.validate = function(fieldName, callback) {
        if (typeof fieldName === 'function') {
          callback = fieldName;
          _validateForm(callback);
        } else if (typeof fieldName === 'string') {
          _validateField(fieldName, callback);
        }
        return this;
      };
      return this;
    };
    return window.Eim = Eim;
  })(window);

}).call(this);
